### ISSUE TITLE
natchez sttp module

### ISSUE THREAD

**Issue by Fristi** [ovotech/natchez-extras#50]
Would there be interest in a sttp module for natchez?

**Comment by Fristi** [comment]
Or would we rather contribute this to sttp itself?

**Comment by mwz** [comment]
We seem to have only a handful of services using sttp so probably not too much interest from our end, but on the other hand I don't see why not if you're keen to contribute.

@tomverran has a majority vote here so you'll need his blessing, although I think he's a fan of sttp 😄
