### ISSUE TITLE
TraceMiddleware HttpRoutes support

### ISSUE THREAD

**Issue by user753** [ovotech/natchez-extras#54]
I would be great if TraceMiddleware could work with `Http` instead of `HttpApp`, so it could be used with `HttpRoutes`.

**Comment by tdbgamer** [comment]
We just submitted a PR for supporting HttpRoutes:
https://github.com/ovotech/natchez-extras/pull/59

**Comment by tdbgamer** [comment]
Looks like this issue is addressed:
https://github.com/ovotech/natchez-extras/pull/59#issuecomment-833675137

**Comment by tomverran** [comment]
Hi, sorry I didn't respond to this earlier - indeed hopefully my comment on #59 explains why we have to trace `HttpApp` - I've added a tiny bit of syntax & updated the docs to include a guide for tracing only some routes (which I think is the main reason to want to trace `HttpRoutes`) https://ovotech.github.io/natchez-extras/docs/natchez-http4s.html#tracing-only-some-routes
