### ISSUE TITLE
Headers not compatible with B3 Propagation

### ISSUE THREAD

**Issue by tdbgamer** [ovotech/natchez-extras#63]
We noticed the services we migrated to this stopped tracing properly with services written in other languages using builtin datadog tracing. The issue is the headers in the Kernel aren't named according to the B3 Propagation standard:
https://github.com/openzipkin/b3-propagation

Looks like datadog supports a bunch of headers for reference:
https://github.com/DataDog/dd-trace-java/blob/614976ed2cbcef3b528b1a0eca3f06b8eb1dab54/dd-java-agent/instrumentation/opentelemetry/src/main/java/datadog/trace/instrumentation/opentelemetry/OtelContextPropagators.java#L67-L78

**Comment by tomverran** [comment]
Hi, thanks for reporting this! I've had a quick look at adding the headers and it seems it'll need a tiny bit of work in that we need to handle propagating both a parent and current span ID (currently the span ID becomes the parent span ID during propagation) as per the docs: https://github.com/openzipkin/b3-propagation#why-is-parentspanid-propagated

I'll have a go at working on this next Friday

**Comment by slivkamiro** [comment]
Hi, is this issue going to add support for `x-datadog-parent-id` and `x-datadog-trace-id` headers too?

**Comment by tdbgamer** [comment]
Hey just checking in, any updates on this?

**Comment by tomverran** [comment]
Hi yes sorry I never replied, I merged a PR: https://github.com/ovotech/natchez-extras/pull/64 which should have added support for the B3 headers but I'm not able to test this myself beyond the unit tests I wrote - let me know if you do come across any issues though!

**Comment by tdbgamer** [comment]
awesome, thanks!

**Comment by tomverran** [comment]
I'll close this now since the changes were released a while back
