### ISSUE TITLE
Url in natchez-testkit references old effect-utils directory.

### ISSUE THREAD

**Issue by pnadon** [ovotech/natchez-extras#70]
Hello!

[This line](https://github.com/ovotech/natchez-extras/blob/c231233e465c5a2f1b2d036449630eefa1860b83/docs/docs/docs/natchez-testkit.md?plain=1#L25) should probably be changed to [https://github.com/ovotech/natchez-extras/blob/master/natchez-extras-fs2/src/test/scala/com/ovoenergy/natchez/extras/fs2/AllocatedSpanTest.scala](https://github.com/ovotech/natchez-extras/blob/master/natchez-extras-fs2/src/test/scala/com/ovoenergy/natchez/extras/fs2/AllocatedSpanTest.scala).

Great work on the project!

**Comment by tomverran** [comment]
Thanks for flagging @pnadon ! I've fixed it now
