### ISSUE TITLE
Publish natchez-extras-core from the scala 3 branch

### ISSUE THREAD

**Issue by rtimush** [ovotech/natchez-extras#84]
The `7.0.0-M2` artifacts depend on `natchez-extras-core`, but it was not published because of `publish / skip := true`. It would be nice to have it on Maven Central too.

**Comment by emmedema** [comment]
+1

**Comment by voidcontext** [comment]
`6.2.0` has been published this morning, this covers Scala 2. I am going to try to re-integrate this into the scala-3 branch and release a new milestone of the `7.x` line before the weekend.

**Comment by rtimush** [comment]
It looks like `natchez-extras-core` is still not published, most likely because it's not aggregated under the `root` project in `build.sbt`.

**Comment by voidcontext** [comment]
> It looks like `natchez-extras-core` is still not published, most likely because it's not aggregated under the `root` project in `build.sbt`.

This has been fixed, the core package is now available in version `6.2.1` and `7.0.0-M4`.

**Comment by rtimush** [comment]
Thanks!
